#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""!
@file command_lark_builder.py Doxygonコマンド構文定義ファイル生成処理
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import tomllib


SYNTAX_ELEMENTS = {
    "TAG" : "WS tag",
    "TAG?" : "(WS tag)?",
    "DIRECTION" : "WS direction",
    "DIRECTION?" : "(WS direction)?",
    "SENTENCE?" : "(WS sentence)?",
    "NAME" : "WS name",
    "MAIL?" : "(WS mail)?",
    "AUTHOR" : "WS author",
    "TITLE" : "WS title",
}

"""!
@class CommandSpec Doxygonコマンド仕様格納クラス
"""
@dataclass(frozen=True)
class CommandSpec:
    name: str
    syntax: str
    handler: str
    kind: str | None = None

    @property
    def token_name(self) -> str:
        return f"CMD_{self.name.upper()}"

    @property
    def rule_name(self) -> str:
        return f"{self.name}_command"

    @property
    def literal(self) -> str:
        return f"@{self.name}"


"""!
@class CommandLarkBuilder Doxygonコマンド構文定義ファイル生成クラス
"""
class CommandLarkBuilder:
    def __init__(self, specs: list[CommandSpec]) -> None:
        self.specs = specs

    @classmethod
    def from_toml(cls, toml_path: str | Path) -> CommandLarkBuilder:
        toml_path = Path(toml_path)

        with toml_path.open("rb") as f:
            data = tomllib.load(f)

        commands = data.get("commands")
        if not isinstance(commands, dict):
            raise ValueError("command.toml に [commands.xxx] 定義がありません。")

        specs: list[CommandSpec] = []

        for name, raw in commands.items():
            if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
                raise ValueError(f"不正な command 名です: {name!r}")

            if not isinstance(raw, dict):
                raise ValueError(f"[commands.{name}] の定義が不正です。")

            syntax = raw.get("syntax")
            handler = raw.get("handler")
            kind = raw.get("kind")

            if not isinstance(syntax, str) or not syntax.strip():
                raise ValueError(f"[commands.{name}] syntax が未定義です。")

            cls._validate_syntax(name, syntax)

            if not isinstance(handler, str) or not handler:
                raise ValueError(f"[commands.{name}] handler が未定義です。")

            specs.append(
                CommandSpec(
                    name=name,
                    syntax=syntax.strip(),
                    handler=handler,
                    kind=kind,
                )
            )

        return cls(specs)

    @staticmethod
    def _validate_syntax(command_name: str, syntax: str) -> None:
        atoms = syntax.split()

        if not atoms:
            raise ValueError(f"[commands.{command_name}] 構文が空です。")

        for atom in atoms:
            if atom not in SYNTAX_ELEMENTS:
                raise ValueError(
                    f"[commands.{command_name}] 未定義の構文要素です: {atom!r}"
                )

        if atoms.count("SENTENCE?") > 1:
            raise ValueError(
                f"[commands.{command_name}] SENTENCE? を複数指定することはできません。"
            )

        if "SENTENCE?" in atoms and atoms[-1] != "SENTENCE?":
            raise ValueError(
                f"[commands.{command_name}] SENTENCE? は末尾のみ許可します。"
            )

        if "TAG?" in atoms and "TAG" in atoms:
            raise ValueError(
                f"[commands.{command_name}] TAG と TAG? は同時に指定することはできません。"
            )

        if "DIRECTION?" in atoms and "DIRECTION" in atoms:
            raise ValueError(
                f"[commands.{command_name}] DIRECTION と DIRECTION? は同時に指定することはできません。"
            )
        if "MAIL?" in atoms and atoms[-1] != "MAIL?":
            raise ValueError(
                f"[commands.{command_name}] MAIL? は末尾のみ許可します。"
            )

        if "AUTHOR" in atoms and (len(atoms) != 1):
            raise ValueError(
                f"[commands.{command_name}] AUTHOR を複数することはできません。"
            )

        if "TITLE" in atoms and (len(atoms) != 1):
            raise ValueError(
                f"[commands.{command_name}] TITLE を複数指定することはできません。"
            )

    def build(self) -> str:
        lines: list[str] = []

        lines.extend(
            [
                "// ============================================================",
                "// command.lark - Doxygonコマンド構文定義ファイル",
                "//",
                "// Source: config/command.toml",
                "// This file is generated automatically.",
                "// Do not edit this file directly.",
                "// ============================================================",
                "",
                "start: command_header",
                "",
                "command_header: known_command",
                "              | unknown_command",
                "",
            ]
        )

        for i, spec in enumerate(self.specs):
            if i == 0:
                lines.append(f"known_command: {spec.rule_name}")
            else:
                lines.append(f"             | {spec.rule_name}")

        lines.append("")

        for spec in self.specs:
            lines.append(self._build_command_rule(spec))

        lines.extend(
            [
                "",
                "unknown_command: AT_COMMAND (WS sentence)?",
                "",
                "tag: TAG",
                "name: NAME",
                "mail: MAIL",
                "author: AUTHOR_TEXT",
                "direction: PARAM_DIR",
                "sentence: TEXT",
                "title: TITLE",
                "",
                self._build_tokens(),
                "",
                "AT_COMMAND.1: \"@\" /[A-Za-z_][A-Za-z0-9_]*/",
                "",
                "PARAM_DIR: \"[\" DIRECTION \"]\"",
                "DIRECTION: \"in\" | \"out\" | \"in,out\" | \"out,in\"",
                "MAIL: /[^ \\t\\r\\n@<>]+@[^ \\t\\r\\n@<>]+/",
                "AUTHOR_TEXT: /[^\\r\\n]+/",
                "TITLE: /[^\\r\\n]+/",
                "NAME: /[^ \\t\\r\\n@][^ \\t\\r\\n]*/",
                "TAG: /[^ \\t\\r\\n@][^ \\t\\r\\n]*/",
                "TEXT: /[^\\r\\n]+/",
                "WS: /[ \\t]+/",
                "",
            ]
        )

        return "\n".join(lines)

    def _build_command_rule(self, spec: CommandSpec) -> str:
        if spec.name == "author" or spec.syntax == "AUTHOR":
            return f"{spec.rule_name}: {spec.token_name} WS author"

        parts = self._syntax_to_lark_parts(spec.syntax)
        if parts:
            return f"{spec.rule_name}: {spec.token_name} {parts}"

        return f"{spec.rule_name}: {spec.token_name}"

    def _syntax_to_lark_parts(self, syntax: str) -> str:
        atoms = syntax.split()
        parts: list[str] = []

        for _index, atom in enumerate(atoms):
            if atom in SYNTAX_ELEMENTS:
                parts.append(SYNTAX_ELEMENTS[atom])
            else:
                raise ValueError(f"構文に誤りがあります: {atom!r}")

        return " ".join(parts)

    def _build_tokens(self) -> str:
        lines: list[str] = []

        for spec in self.specs:
            lines.append(f"{spec.token_name}.10: \"{spec.literal}\"")

        return "\n".join(lines)

    def write(self, output_path: str | Path) -> None:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.build(), encoding="utf-8")


"""!
@fn generate_command_lark Doxygonコマンド構文定義ファイル生成処理
@brief Doxygonコマンド定義ファイルを読み込み、Doxygonコマンド構文定義ファイルを生成する。
@param [in] toml_path Doxygonコマンド定義ファイルの入力元パス
@param [in] output_path Doxygonコマンド構文定義ファイルの出力先パス
"""
def generate_command_lark(
    toml_path: str | Path = "config/command.toml",
    output_path: str | Path = "generated/command.lark",
) -> None:
    builder = CommandLarkBuilder.from_toml(toml_path)
    builder.write(output_path)
